version: "3.8"

services:
  webapp1:
    image: tamarar/cloud_computing
    container_name: webapp1
    restart: on-failure
    env_file: 
      - ./env/webapp1.env
    depends_on:
      - postgres1
    networks:
      - app2db1

  webapp2:
    image: tamarar/cloud_computing
    container_name: webapp2
    restart: on-failure
    env_file: 
      - ./env/webapp2.env
    depends_on:
      - postgres2
    networks:
      - app2db2

  postgres1:
    image: postgres:14
    container_name: postgres1
    restart: on-failure
    env_file: 
      - ./env/db1.env
    networks:
      - app2db1
    volumes:
      - /var/lib/postgresql/data
      
  postgres2:
    image: postgres:14
    container_name: postgres2
    restart: on-failure
    env_file: 
      - ./env/db2.env
    networks:
      - app2db2
    volumes:
      - /var/lib/postgresql/data

  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
    networks:
      - app2db1
      - app2db2

networks:
  app2db1:
    driver: bridge
  app2db2:
    driver: bridge