# Generated by Django 3.2.9 on 2021-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='durationInMinutes',
        ),
        migrations.AddField(
            model_name='song',
            name='performedBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
