version: "3.8"

services:

  webapp:
    image: tamarar/cloud_computing:0.1
    container_name: webapp
    restart: on-failure
    ports:
      - 8000:8000
    env_file: 
      - ./env/webapp.env
    depends_on:
      - postgres
    networks:
      - app2db

  postgres:
    image: postgres:14
    container_name: postgres
    restart: on-failure
    env_file: 
      - ./env/db.env
    networks:
      - app2db
    volumes:
      - /var/lib/postgresql/data

networks:
  app2db:
    driver: bridge